### ISSUE TITLE
[Icarus] Im Alt Manager "From Files" funktioniert nicht. Stürzt ab

### ISSUE THREAD

**Issue by JakobsCode** [xKeksbyte/icarus-issue-tracker#10]
Hallo,
Wenn man im Alt Manager auf "From Files" klickt, stürzt das Spiel ab. Hier ein Video davon was ich aufgenommen habe: https://videobin.org/+1a9o/1gkq.ogg
Hier die Logs [Sind die letzten bis zum Ende, kann also sein, das die nix bringen]:

ERROR OldServerPinger Can't ping timolia.de: Internal Exception: java.io.IOException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
ERROR GuiScreen Couldn't open link java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.client.gui.GuiScreen.openWebLink(GuiScreen.java:596)
	at net.minecraft.client.gui.GuiScreen.handleComponentClick(GuiScreen.java:372)
	at net.minecraft.client.gui.GuiChat.mouseClicked(GuiChat.java:184)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:502)
	at net.minecraft.client.gui.GuiChat.handleMouseInput(GuiChat.java:150)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:479)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1506)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:948)
	at net.minecraft.client.Minecraft.run(Minecraft.java:385)
	at net.minecraft.client.main.Main.main(Main.java:114)
	at Start.main(Start.java:14)
Caused by: java.io.IOException: Failed to open file:/C:/Users/jakob/AppData/Roaming/.minecraft/./screenshots/2020-06-29_15.23.10.png. Error message: Das System kann die angegebene Datei nicht finden.

	at sun.awt.windows.WDesktopPeer.ShellExecute(WDesktopPeer.java:90)
	at sun.awt.windows.WDesktopPeer.browse(WDesktopPeer.java:76)
	at java.awt.Desktop.browse(Desktop.java:385)
	... 15 more

ERROR GuiScreen Couldn't open link java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.client.gui.GuiScreen.openWebLink(GuiScreen.java:596)
	at net.minecraft.client.gui.GuiScreen.handleComponentClick(GuiScreen.java:372)
	at net.minecraft.client.gui.GuiChat.mouseClicked(GuiChat.java:184)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:502)
	at net.minecraft.client.gui.GuiChat.handleMouseInput(GuiChat.java:150)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:479)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1506)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:948)
	at net.minecraft.client.Minecraft.run(Minecraft.java:385)
	at net.minecraft.client.main.Main.main(Main.java:114)
	at Start.main(Start.java:14)
Caused by: java.io.IOException: Failed to open file:/C:/Users/jakob/AppData/Roaming/.minecraft/./screenshots/2020-06-29_15.23.10.png. Error message: Das System kann die angegebene Datei nicht finden.

	at sun.awt.windows.WDesktopPeer.ShellExecute(WDesktopPeer.java:90)
	at sun.awt.windows.WDesktopPeer.browse(WDesktopPeer.java:76)
	at java.awt.Desktop.browse(Desktop.java:385)
	... 15 more

ERROR GuiScreen Couldn't open link java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.client.gui.GuiScreen.openWebLink(GuiScreen.java:596)
	at net.minecraft.client.gui.GuiScreen.handleComponentClick(GuiScreen.java:372)
	at net.minecraft.client.gui.GuiChat.mouseClicked(GuiChat.java:184)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:502)
	at net.minecraft.client.gui.GuiChat.handleMouseInput(GuiChat.java:150)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:479)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1506)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:948)
	at net.minecraft.client.Minecraft.run(Minecraft.java:385)
	at net.minecraft.client.main.Main.main(Main.java:114)
	at Start.main(Start.java:14)
Caused by: java.io.IOException: Failed to open file:/C:/Users/jakob/AppData/Roaming/.minecraft/./screenshots/2020-06-29_15.23.10.png. Error message: Das System kann die angegebene Datei nicht finden.

	at sun.awt.windows.WDesktopPeer.ShellExecute(WDesktopPeer.java:90)
	at sun.awt.windows.WDesktopPeer.browse(WDesktopPeer.java:76)
	at java.awt.Desktop.browse(Desktop.java:385)
	... 15 more

ERROR EntityItem Item entity 38823 has no item?!
ERROR EntityItem Item entity 38823 has no item?!
ERROR EntityItem Item entity 38882 has no item?!
ERROR EntityItem Item entity 39408 has no item?!
ERROR EntityItem Item entity 39408 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897947 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1897968 has no item?!
ERROR EntityItem Item entity 1898114 has no item?!
ERROR EntityItem Item entity 1898114 has no item?!
ERROR EntityItem Item entity 1898165 has no item?!
ERROR EntityItem Item entity 1898165 has no item?!
ERROR EntityItem Item entity 113504 has no item?!
ERROR EntityItem Item entity 118205 has no item?!
ERROR EntityItem Item entity 113509 has no item?!
ERROR EntityItem Item entity 118201 has no item?!

**Comment by xKeksbyte** [comment]
Weil die datei nicht existiert..

//closed

**Comment by xKeksbyte** [comment]
Habe das problem auch.
Werde es fixen, danke für den report C:
