### ISSUE TITLE
Icarus b19 startet nicht

### ISSUE THREAD

**Issue by Akorian** [xKeksbyte/icarus-issue-tracker#28]
Icarus b19 startet nicht.
ClientLauncher <=> Client Icarus launched
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionParser
    at net.minecraft.client.main.Main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionParser
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 2 more

**Comment by Akorian** [comment]
Ok. geht wieder
